### ISSUE TITLE
Tests break on freshly cloned repo

### ISSUE THREAD

**Issue by davidpelaez** [apotonick/trailblazer#101]
Hi Nick.

I was taking a look at the code locally and I couldn't run the tests.

I get this error: `Unable to activate roar-1.0.4, because representable-3.0.0 conflicts with r
epresentable (< 2.4.0, >= 2.0.1) (Gem::ConflictError)`. I see you released reform-2.1.0.rc1 so is probably beause the code is ready to work with that new version but the constraints in roar haven't been updated?

How to make the tests pass? I wanted to see if I could manage to share some of the code we have for Endpoint instead of just complaining on the issues but I couldn't get the initial tests to pass.

**Comment by davidpelaez** [comment]
I wanted to confirm that it's entirely related to the Roar requirement. If I remove the roar gem in the Gemfile and then skip `representer_test.rb` everything goes OK. The exact problem comes from this require https://github.com/apotonick/trailblazer/blob/master/test/representer_test.rb#L39

**Comment by apotonick** [comment]
Yeah, you have to point to `roar/master` until I release 1.1. Thanks! :beers:
