### ISSUE TITLE
Trailblazer does not recognize subclassed models

### ISSUE THREAD

**Issue by byrnejb** [apotonick/trailblazer#104]
In an existing project I have a model the looks like this:

    class GLTransaction < ActiveRecord::Base
      . . .
    end

and a sub-classed model that looks like this:

    class ARInvoice < GLTransaction
      has_many( :ar_invoice_details )
    end

I am trying out Trailblazer and I have created `app/concepts/ar_invoice/operation.rb` that looks like this:

    class ARInvoice < GLTransaction
      class Create < trailblazer::Operation
        def process( params )
         @model = ARInvoice.create( params[ :ar_invoice ] )
        end
      end
    end

And a crud_test.rb that looks like this:

    class ARInvoiceCrudTest < MiniTest::Spec
      describe( "Create" ) do
        it( "persists valid" ) do
          ar_invoice = ARInvoice::Create.(
          :ar_invoice => { :invoice_number => 101,
                           :client_number => 1234
            }
          ).model

          ar_invoice.persisted?.must_equal( true )
          ar_invoice.invoice_number.must_equal( 102 )
          ar_invoice.client_number.must_equal( 5678 )
        end
      end
    end

When this is run `bundle rake test test/concepts/ar_invoice/crud_test.rb` I see this:

    rake aborted!
    NameError: undefined local variable or method `trailblazer' for ARInvoice (call
    'ARInvoice.connection' to establish a connection):Class`

This is no doubt caused by the sub-classing of ARInvoice from GLTransaction.  However, this sub-classing works for my existing cucumber features without complaint.  What additional configuration is required for Trailblazer or what am I doing wrong that causes this error?

**Comment by apotonick** [comment]
`class Create < trailblazer::Operation` must be `class Create < Trailblazer::Operation`. Too many :beers:?

**Comment by byrnejb** [comment]
If only.  Thanks for the eyeballs.
