### ISSUE TITLE
Do you know any big open source projects using Trailblazer?

### ISSUE THREAD

**Issue by phortx** [apotonick/trailblazer#107]
For reading some real Code examples.

**Comment by alexvbush** [comment]
Yeah, I'd like to see something like that too

**Comment by apotonick** [comment]
Same here! :grimacing: :laughing:

**Comment by apotonick** [comment]
We started this yesterday, let's see who's in! http://trailblazer.to/users.html

**Comment by phortx** [comment]
Very nice! I'll send you mine as soon as it's published on GitHub ;)
