### ISSUE TITLE
params! - `!` is supposed to mean what it returns does not matter?

### ISSUE THREAD

**Issue by ramontayag** [apotonick/trailblazer#111]
For this method, it matters what you return though. But renaming it to `params` would not be good because that's the instance variable name and it will be confusing. Why not direct people to just override `assign_params!` if they want to change the params instead?

**Comment by apotonick** [comment]
I started to introduce that pattern in all my gems, I wasn't aware that I am messing up with conventions (again): `#model!`, `#params!`, `#policy!` and so on, they all mean "the return value is important and will replace the internal concept named after the method name. It's *not* your duty to assign the value to anything, we do it for you".

**Comment by apotonick** [comment]
Oh, and `assign_params!` is the wrong method, because in that method, you have to **assign** the return value to an instance variable, too (as the name implies).

**Comment by ramontayag** [comment]
That's right... ok, well, yeah that's something to note: For `params!` and a few other `!` methods, what is returned matters. Thanks!
