### ISSUE TITLE
Operation.contract(SomeFormClass) behaves differently than Operation.contract_class = SomeFormClass

### ISSUE THREAD

**Issue by niels** [apotonick/trailblazer#112]
I would expect both both of these operations to have the same result:

```ruby
class Operation < Trailblazer::Operation
  contract ::Form
end
```

```ruby
class Operation < Trailblazer::Operation
  self.contract_class = ::Form
end
```

However, they behave significantly differently. The first option seems to overwrite / ignore all of `::Form`'s instance methods:

```ruby
class Form < Reform::Form
  property :custom_setter

  def custom_setter=(str)
    super(str.to_s.upcase)
  end
end

class OperationUsingContract < Trailblazer::Operation
  contract ::Form
end

class OperationUsingContractClass < Trailblazer::Operation
  self.contract_class = ::Form
end

form_using_contract = OperationUsingContract.contract_class.new(OpenStruct.new)
form_using_contract.validate(custom_setter: "lowercase")
puts form_using_contract.custom_setter #=> "lowercase", but expected "LOWERCASE"

form_using_contract_class = OperationUsingContractClass.contract_class.new(OpenStruct.new)
form_using_contract_class.validate(custom_setter: "uppercase")
puts form_using_contract_class.custom_setter #=> "UPPERCASE" (correct / expected)
```

If this is a WONTFIX, I would suggest updating the documentation accordingly.

Also, the underlying cause for this is probably in how reform or disposable handle inheritance or mixins (after all, `Operation.contract` will actually subclass the passed in class), but I'm not sure.

**Comment by niels** [comment]
Note that using in-line contracts will fail similarly. But that's perhaps acceptable in this case. I would be OK with requiring explicit contract / Form classes for such "advanced" functionality; as long as it is clearly documented.

```ruby
class ParentOperation < Trailblazer::Operation
  contract do
    property :custom_setter

    def custom_setter=(str)
      super(str.to_s.upcase)
    end
  end
end

class SubOperation < ParentOperation
  contract do
    property :an_additional_property
  end
end

sub_contract = SubOperation.contract_class.new(OpenStruct.new)
sub_contract.validate(custom_setter: "lowercase")
puts sub_contract.custom_setter #=> "lowercase", but expected "LOWERCASE"

parent_contract = ParentOperation.contract_class.new(OpenStruct.new)
parent_contract.validate(custom_setter: "uppercase")
puts parent_contract.custom_setter #=> "UPPERCASE" (correct / expected)
```

**Comment by niels** [comment]
:no_good: Sorry for the SPAM!

One final addendum:

It seems as if currently, subclassing 

The intermediate cause for this is the use of `Class.new` in `Operation.contract`. When using either `Cl

**Comment by niels** [comment]
Let's track this in https://github.com/apotonick/disposable/issues/36 instead.

**Comment by apotonick** [comment]
Thanks @niels! The issue is that `contract FormClass` will *subclass* `FormClass` whereas the setter `Operation::contract_class=` will simply assign the constant. The bug lies within Disposable's subclassing as you correctly referred to in your last comment. :beer:
