### ISSUE TITLE
Book typos

### ISSUE THREAD

**Issue by jerefrer** [apotonick/trailblazer#117]
Hi @apotonick 

I just finished reading the book and I have to say there's a lot of great ideas in it ... Thanks for all the experimentations and hard work you put into it !
As you said I might need to let it sink a bit. I think I'll wait for the next decently-complex feature request to pop up and try to use Trailblazer to implement parts of it. Would you have some recommendations on just this ?

Anyway, alongside my reading I filled [this Google Sheet](https://docs.google.com/spreadsheets/d/1NwlCz4rbqpHcC-zG0hm2JMhkA4zz_9DVG5rdXD9_ulA/edit?usp=sharing) with a few typos and inconsistencies I found.

A humble attempt to repay for your efforts. :bow:

**Comment by peterhoeg** [comment]
Further to @jerefrer's comments on @apotonick's book, it would be great if you could run:

```s/gonna/going to/g```

on the source material

**Comment by apotonick** [comment]
Ok, finally, I managed to incorporate all your fixes @jerefrer and I have to say, I'm impressed by your work. This was an amazing help, thank you so much for going through all this with that fine-toothed comb :joy: ! 

I would like to offer you a year of free membership for Trailblazer Pro (coming soon). Let me know if you're interested? :heart: 

@peterhoeg Done! Only 75 replaces :lowersheadinshame:.

**Comment by jerefrer** [comment]
Haha I'm touched by the kind word but really it's nothing compared to the time I imagine you put into all this.

Thank you @apotonick for incorporating them !

Of course I'd be happy to get some free stuff (who isn't ?!), even though I don't know what it is !
Anyway, now I can't wait to know more :open_mouth:.

PS: I don't know if this Pro thing would include screencasts, but I think it would be a great addition to the TB world. Having been a fan of Railscasts when I first learned Rails, I really felt that the lack of them with TB hold me back in my learning process.
Please, screencasts ? :wink:

**Comment by apotonick** [comment]
Would love to do screencasts - if this whole TRB thing starts paying off, I will have time for more learning content.

**Comment by jerefrer** [comment]
Ok no worries, I'll dig into the book !

I wish you quick and huge success with what's coming ! :tada:

**Comment by apotonick** [comment]
This is Pro: https://trbpro.herokuapp.com/ :tada:
