### ISSUE TITLE
Handling Operation Models in Cells

### ISSUE THREAD

**Issue by fernandes** [apotonick/trailblazer#120]
__problem__

in some complex view, you need to render a cell for `@model`, sometimes for its form using `@form` ok... but in some operation you need more objects to render on some cells, imagine something like:

```ruby
-----------------------
| Profile              |
-----------------------
| Address | Friends    |
|         |            |
|         |            |
|----------------------|
```

where you have three cells that need 3 different objects

__context__

In our app we usually bound ONE operation to one controller action, and each action render its cell, and inside that cell we can render other cells, but we keep the organization base on route-controller-concept to keep our sanity

sometimes in `/user/profile` route we have:

```ruby
class UserController
  def profile
    present User::Show
  end
end
```

```ruby
class User::Show < Trailblazer::Operation
  def model!
    user = User.find(params[:id])
    friends = Friend.all
    addresses = user.addresses
    OpenStruct.new(user: user, friends: friends, addresses: addresses)
  end
end
```

the `UserController#profile` that renders `User::ProfileCell` we call `present User::Show` it sets the model and everybody is happy. But if you need 3 models like in the cells example above we set a OpenStruct inside `model!` its _no_ good, but the only way to send our needed models to view.

It works fine until kind of update action where you need the `@model` inside `process`

__solution__

When we can't set the model (and now we are adopting as default in our operations), we set a `attr_reader :view` on operation and put everything we need inside, like:

```ruby
class User::Update < Trailblazer::Operation
  def process(params)
    @model.update
    friends = Friend.all
    addresses = @model.addresses
    @view = OpenStruct.new(user: @model, friends: friends, addresses: addresses)
  end

  def model!
    User.find(params[:id])
  end
end
```

then we send the operation to be rendered by the cell, and we can call:

```erb
<%= concept('user/profile/user', model: model.view.user %>
<%= concept('user/profile/address', collection: model.view.addresses %>
<%= concept('user/profile/friends', model: model.view.friends %>
```

ps: calling `model.` to make it explicity

__conclusion__

It has become a really great pattern in our application, so every action (route) in our application is bounded to one controller, one operation and one cell, if we need to send more models to view, we set on operation `view` and cell handles it.

So I'm opening this _really long_ issue to discuss if this is a good pattern, and if you'd like to add something like this on trailblazer 😉

**Comment by fernandes** [comment]
I did the smallest implementation possible to this problem:

```ruby
require 'trailblazer/operation'

class Trailblazer::Operation
  attr_reader :view

  def view_store(key, object)
    @view = OpenStruct.new if @view.nil?
    @view.send("#{key}=", object)
  end
end
```

So inside an operation you just need to:

```ruby
view_store(:my_object, Thing.all)
```

then in your ~~view~~ cell you just need to call:

```ruby
<%= operation.view.my_object %>
```

hope it helps someone else! 😎

**Comment by apotonick** [comment]
We will soon introduce `Endpoint` that does this, as the operation shouldn't know about presentation! So, the endpoint will be able to use representers for APIs and cells for views.

**Comment by fernandes** [comment]
great! actually I'm using operations inside `app/concepts` as `Endpoints`, and my operations related to models are inside `app/models/:model/:verb`, this is great

but not overloading `operation` with presentation knowledge is cool because we don't need to worry about setting view variables on operations inside `app/models` operations

ps: an operation organizer is a must on endpoints :)
