### ISSUE TITLE
Donations?

### ISSUE THREAD

**Issue by benlovell** [apotonick/trailblazer#125]
Hey, I'm a huge fan of this project and would like to contribute financially. First off - do you have anything setup to take donations and if not, is this something you'd consider? Check hanami/hanami#560 for some pointers if this is something you'd be willing to add.

Thanks for all you do, it's very much appreciated ❤️  💛  💚

**Comment by apotonick** [comment]
That is very sweet of you! I am in the process of setting up a company, and we will soon have *Trailblazer Pro* which is a monthly plan. I hope this is what you're after? Thanks again :heart:

**Comment by benlovell** [comment]
Works for me. Cheers 🍻

**Comment by apotonick** [comment]
Hey love, the first minimalistic version is here: http://pro.trailblazer.to :grimacing:

**Comment by benlovell** [comment]
😍
