### ISSUE TITLE
Unable to call operation without arguments

### ISSUE THREAD

**Issue by contentfree** [apotonick/trailblazer#134]
For a rake task, I created an operation that requires no parameters. When I tried to call it in the least surprising way – `MyOperation.()`  – an `ArgumentError: wrong number of arguments (0 for 1)` is raised. 

Could [`Operation#call`](https://github.com/apotonick/trailblazer/blob/master/lib/trailblazer/operation.rb#L33) provide `params = {}` instead of requiring the argument?

**Comment by apotonick** [comment]
Hi @contentfree, yepp, passing an empty `{}` is the desired API presently. This might change in 1.2 since we make operation's work with dry-rb's `auto_inject` and thus change to kw args.

**Comment by apotonick** [comment]
Oh, to make that better understandable: Until yesterday, there wasn't any specification about how TRB operation inputs are structured, you could basically pass in any kind of object or number of args, which contradicted a `params = ...` defaulting.

**Comment by contentfree** [comment]
So would `process(**params)` handle both the empty params as well as leaving the specification open?
