### ISSUE TITLE
Operations vs Interactors

### ISSUE THREAD

**Issue by onemanstartup** [apotonick/trailblazer#18]
It seems it is the same concept like in https://github.com/collectiveidea/interactor , but I did not find features like organizers from that game. Running other operations-interactors from another. Is it by design? I will need doing this manually?

Also there are hooks, rollbacks, contexts, logging (in this gem https://github.com/adomokos/light-service), translations (https://github.com/orgsync/active_interaction). So many features, so many gems it very easy to be confused. For example one question is why operations in trailblazer embedded unlike reform or cells, it seems belong to another gem.

I hope I don't entirely missed the point, just hope for clarification from author. Thanks.

**Comment by apotonick** [comment]
My opinion here is to use gems like `dry-transaction` or `active_interaction` from within an operation. We might provide some sugar to integrate them more easily, but so far I've been very happy using `dry-transaction` as a completely decoupled object in my operations.

**Comment by DanielStevenLewis** [comment]
@apotonick Is your recommendation in 2019 still to use `dry-transaction` or `active_interaction` within an `operation` if one wants to implement a chain of responsibility pattern (like with an `organizer` from the `interactor` gem)? Thanks.

**Comment by mensfeld** [comment]
@DanielStevenLewis dry transaction won't be maintained beyond 1.0

**Comment by apotonick** [comment]
@DanielStevenLewis Absolutely not, use Trailblazer's operations (or activities, as they're called in 2.10). We've progressed massively since this discussion 3 years ago. Here's a preview of new docs: http://2019.trailblazer.to/2.1/docs/activity.html

**Comment by apotonick** [comment]
@DanielStevenLewis New tutorials are now ready, and they show how activities work for any kind of business flow, from simple CRUD to complex long-running life cycles. http://2019.trailblazer.to/2.1/tutorials/activity.html
