### ISSUE TITLE
Quick question: how tied into Rails is this framework?

### ISSUE THREAD

**Issue by matthewsinclair** [apotonick/trailblazer#22]
Hi - a quick question: I'm wondering how tied into Rails this framework is? 

The reason I ask is that I think it looks really promising and I'd love to use it, but I want to use it in a Rails project _as well as_ inside my client, which is RubyMotion iOS app. 

All of the same issues that you're solving here with Trailblazer come up in one form or another in RubyMotion as well. So, I was wondering if it would be possible to build as much of the business logic layer as I could in POROs which would work in both Rails and RM, and then just cope with the platform-specific stuff myself.

Thoughts?

**Comment by fernandes** [comment]
@matthewsinclair can we close this?

**Comment by matthewsinclair** [comment]
Sure. I thought it was closed, to be honest. :)

**Comment by apotonick** [comment]
As a side-note: we really need to clarify this in the README: many people I've spoken to in the last weeks at conferences thought that Trb requires ActiveRecord and didn't understand that this is a mash-up of gems with no/minimal dependencies between each other. E.g. Cells is totally optional.
