### ISSUE TITLE
Doesn't play nice with Spring in test environment?

### ISSUE THREAD

**Issue by cgaudreau** [apotonick/trailblazer#29]
I have this in application.rb:

require "trailblazer/rails/railtie"

Let's say I run bin/rspec which uses Spring under the hood. The first time, the tests will pass. However, if I try to change, for example, app/concepts/thing/crud.rb, then it gives me the following error:

uninitialized constant Thing::Create (NameError)

I'm sure I'm just doing something wrong, but anyway, if I change Rails.configuration.cache_classes in config/environments/test.rb to false (defaults to true in new rails projects) then it magically works.

Also, if I replace the above require with

```ruby
module Trailblazer
  class Railtie < Rails::Railtie
    def self.autoload_crud_operations(app)
      Dir.glob("app/concepts/**/crud.rb") do |f|
        path  = f.sub("app/concepts/", "")
        model = path.sub("/crud.rb", "")

        require_dependency "#{app.root}/app/models/#{model}" # load the model file, first (thing.rb).
        require_dependency "#{app.root}/#{f}" # load app/concepts/{concept}/crud.rb (Thing::Create, Thing::Update, and so on).
      end
    end

    # thank you, http://stackoverflow.com/a/17573888/465070
    initializer 'trailblazer.install', after: :load_config_initializers do |app|
      # the trb autoloading has to be run after initializers have been loaded, so we can tweak inclusion of features in
      # initializers.
      # if Rails.configuration.cache_classes
      #   Trailblazer::Railtie.autoload_crud_operations(app)
      # else
        ActionDispatch::Reloader.to_prepare do
          Trailblazer::Railtie.autoload_crud_operations(app)
        end
      # end
    end
  end
end
```

then it works. (with or without cache_classes set to true) Note that I simply made it so autoload_crud_operations always runs within ActionDispatch::Reloader.to_prepare regardless of the value of cache_classes.

In fact, while I'm at it, Thing::Create doesn't seem to update in the console (pry), either. Unless I invoke ```reload!```.

**Comment by zavan** [comment]
You don't need that line: `require "trailblazer/rails/railtie"` anywhere.
Rails does that for you.

**Comment by cgaudreau** [comment]
You seem to be right about pry not having auto-reloading, sorry about that. Working while tired is a bad idea.

**Comment by zavan** [comment]
Just to make sure, you did put `require "trailblazer/rails/railtie"` ***at the end*** of `application.rb`, right?

**Comment by cgaudreau** [comment]
Yeah, it's on the last line. Rails 4.2, Ruby 2.2. Project was created earlier today.

```bin/rspec``` works until I modify ```crud.rb```. If I run stop the Spring server, the specs pass again, until I modify ```crud.rb```.

**Comment by zavan** [comment]
Well, then it's probably a bug because of the `if` part commented in this block:


```ruby
initializer 'trailblazer.install', after: :load_config_initializers do |app|
  # the trb autoloading has to be run after initializers have been loaded, so we can tweak inclusion of features in
  # initializers.
  # if Rails.configuration.cache_classes
  #   Trailblazer::Railtie.autoload_crud_operations(app)
  # else
    ActionDispatch::Reloader.to_prepare do
      Trailblazer::Railtie.autoload_crud_operations(app)
    end
  # end
end
```

(It's uncommented from where Nick took this: http://stackoverflow.com/questions/7504744/how-do-i-hook-into-rails-after-files-are-reloaded-on-each-request-in-developme/17573888#17573888 and this is related to the `cache_classes` being true or false... So I'm guessing here lies the problem.)

I can have look tomorrow, if @apotonick doesn't have this fixed till then, but I've never poked around rails autoloading before, gon' need some research.

**Comment by cgaudreau** [comment]
For what it's worth, changing it to this seems to fix it in all contexts for me:

```ruby
module Trailblazer
  class Railtie < Rails::Railtie
    def self.autoload_crud_operations(app)
      Dir.glob("app/concepts/**/crud.rb") do |f|
        path  = f.sub("app/concepts/", "")
        model = path.sub("/crud.rb", "")

        require_dependency "#{app.root}/app/models/#{model}" # load the model file, first (thing.rb).
        require_dependency "#{app.root}/#{f}" # load app/concepts/{concept}/crud.rb (Thing::Create, Thing::Update, and so on).
      end
    end

    config.to_prepare do
      Trailblazer::Railtie.autoload_crud_operations(Rails.application)
    end
  end
end```

Just a quick late night hack, so I'm sure I've done something dumb. Time to sleep.

**Comment by apotonick** [comment]
Hm... @pixeltrix, sorry to bother you, but is that the way Rails' autoloading and `require_dependency` is supposed to work? We used to distinguish as follows.

```ruby
if Rails.configuration.cache_classes
  Trailblazer::Railtie.autoload_crud_operations(app)
else
  ActionDispatch::Reloader.to_prepare do
    Trailblazer::Railtie.autoload_crud_operations(app)
  end
end
``` 

But now that I think about it, `require_dependency` simply doesn't get invoked, again, in production, does it? Thanks you guys!!! :heart: :beers:

**Comment by pixeltrix** [comment]
@apotonick that's correct, there's no need to protect it - `to_prepare` will only be called once in production.

**Comment by apotonick** [comment]
@pixeltrix, @cgaudreau and @zavan : you guys rock! Thanks!

**Comment by townhouse** [comment]
I'm still running into this issue whilst using spring with Rails 4.2.1 and trailblazer/master. Only spring stop/start loads operations and lets me run tests.
