### ISSUE TITLE
Namespacing issues

### ISSUE THREAD

**Issue by christianonrails** [apotonick/trailblazer#30]
Hi,

I read the trailblazer book and now I'm playing around with it. Architecture-wise I'm absolutely convinced about the idea. However, I got in some problems when I try to namespace something. I copied your example app and created an admin namespace in routes. and i added also an admin folder with all the files in controller, concept and view. 

When I hit the new action of admin/things_controller

def new
  present Thing::Create
end

I get this:
uninitialized constant Thing::Create

Do you have any ideas?

**Comment by apotonick** [comment]
Hi Christian,

I document what is not in the book (yet, because in flux) here: https://github.com/apotonick/gemgem-trbrb/wiki/Things-You-Should-Know

You need to include the railtie. Let me know how it goes!

**Comment by christianonrails** [comment]
Thanks for letting me know. I put this in the application.rb

require 'trailblazer/rails/railtie'

but when I try to start the server i get this:

=> Booting Thin
=> Rails 4.2.0 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Exiting
bin/rails:6: warning: already initialized constant APP_PATH
/home/christian/Work/sporthorses_moeller/bin/rails:6: warning: previous definition of APP_PATH was here

**Comment by christianonrails** [comment]
I researched it a bit and I had to do this: rake rails:update:bin
And I had to take out require 'trailblazer/crud_autoloading' from the trailblazer initializer. At least server is running now. I'll test whether modules are working

**Comment by christianonrails** [comment]
Still no success :(

**Comment by apotonick** [comment]
Wait, `trailblazer/crud_autoloading` doesn't exist anymore, and is not documented anywhere anymore, is it?

Can you test it with Rails 4.1, please?

**Comment by Titinux** [comment]
A reference is still present here :wink: 

https://github.com/apotonick/gemgem-trbrb/blob/master/config/initializers/trailblazer.rb#L11

**Comment by christianonrails** [comment]
yeah thats where i got it from. I basically went through all your commits to understand what you have done

**Comment by apotonick** [comment]
Sorry! I haven't pushed `master` in a long time. I find it very convenient to have one branch per chapter (e.g., right now, I'm working in `chapter-6`), I updated `master`.

**Comment by fernandes** [comment]
hey @christianonrails 

this should be enough for `config/initializers/trailblazer.rb`

```ruby
require 'trailblazer/autoloading'

# I extend the CRUD module here to make it also include CRUD::ActiveModel globally. This is my choice as the
# application architect. Don't do it if you don't use ActiveModel form builders/models.
Trailblazer::Operation::CRUD.module_eval do
  module Included
    def included(base)
      super # the original CRUD::included method.
      base.send :include, Trailblazer::Operation::CRUD::ActiveModel
    end
  end
  extend Included # override CRUD::included.
end
```

ps: I tested with `master` branch, tell me if something wrong.

**Comment by yurifrl** [comment]
I'm having the same issue `uninitialized constant Foo::Index` but in a gem. Also, i'm not finding a place to place: `require 'trailblazer/rails/railtie'`

**Comment by fernandes** [comment]
@yurifrl here is the place: https://github.com/apotonick/gemgem-trbrb/blob/748828cf530ba324a45d67ca55a98e6069cc4960/config/application.rb#L30

probably Foo::Index is in a crud.rb file, no? once railtie is loaded, rails will find Foo::Index :+1:

**Comment by yurifrl** [comment]
@fernandes Right, i'm pretty sure i'm loading it already, but i will verify.
Since i'm using a trb in a gem, can i put it on a initializer?

**Comment by fernandes** [comment]
no... you need to put on your rails app, not on the gem

if this gem is a rails engine you can create a initializer that hooks on rails app (check this rails engine as example https://github.com/railsblocks/railsblocks-auth/blob/master/lib/railsblocks/auth/engine.rb#L38)

**Comment by yurifrl** [comment]
OOOO that's nice, that's real nice, thanks @fernandes i will try it

**Comment by fernandes** [comment]
:sweat_smile:

**Comment by apotonick** [comment]
This should be fixed with `trailblazer-rails` and, automatically included, the `trailblazer-loader` gem.
