### ISSUE TITLE
TypeError (nil is not a symbol nor a string)

### ISSUE THREAD

**Issue by akemrir** [apotonick/trailblazer#31]
hi,

I`am saving nested form and having "TypeError (nil is not a symbol nor a string)" on save in validate.
I does not modify params, they are generated for form by simple_form and operation. Generic hash is passed. This is how part of contract looks.

```ruby 
      collection :campaign_socializations,
        populate_if_empty: -> (fragment, form) {
        CampaignSocialization.where(campaign_id: fragment["campaign_id"], social_target_id: fragment["social_target_id"]).first_or_initialize
      } do
        property :accept, writable: false
        property :campaign_id
        property :social_target_id
      end
```

```haml
          - @targets.each do |target|
            - built = @form.model.campaign_socializations.where({ social_target_id: target.id }).first_or_initialize
            = f.simple_fields_for :campaign_socializations, built do |st|
              = st.input_field :accept, as: :boolean,
                inline_label: target.name, class: "social_target_checkbox",
                checked: @form.model.streams.pluck(:id).include?(target.id)
              = st.input :campaign_id, as: :hidden
              = st.input :social_target_id, as: :hidden
```

It suppose to accept elemenets by virtual property "accept". Sometimes they exists, sometimes not (built).
In form I create formgroups from other model. This should only create connections to predefined items. But I`am getting this error. "TypeError (nil is not a symbol nor a string)"

How can I delete not checked items if they exist?
Is there a way to have more error verbosity in trailblazer?
Sometimes I don't know from where error comes from. It only points to save and that's all.

**Comment by akemrir** [comment]
I have managed to do dirty trick with delete from issue on reform.
But now I'am getting this error on save:
TypeError: nil is not a symbol nor a string
/gems/activemodel-4.2.0/lib/active_model/dirty.rb:181:in `attribute_was'

**Comment by akemrir** [comment]
I have done it. Changed some relations from has_many through to has_many and works.

**Comment by akemrir** [comment]
Is this good idea to place this in concept?

```ruby
    def process(params)
      validate(params[:campaign]) do |f|
        to_be_removed = ->(i) { i.accept == '0' }
        f.model.streams.select(&to_be_removed).map(&:delete)
        f.streams.reject!(&to_be_removed)
        f.save
      end
    end
```

It looks, it works correctly and delete not selected elements from database and also from form.

**Comment by apotonick** [comment]
I have added API semantics to Disposable a few days ago, this will introduce delete, add, replace etc. for collections. Will soon integrate that in Reform.

Your code looks ok - what exactly is the problem? Can you give me more details? Thahanks!

**Comment by akemrir** [comment]
Hi, I have dropped this responsibility back to AR with accepts_nested_attributes_for.
Changed accept to _delete and reversed its meaning in form.

When I was using approach from this issue, there was problems to recognize objects from form by reform. Some of them should be deleted not modified.
For example, form is sending 3 objects:
1. delete false - object exist
2. delete false - object doesnt exist
3. delete true - object exist

And result of this operation is first object in database, second object would be updated with data from third option, with wrong parameters.
Sometimes both second and third would be deleted.

**Comment by the-ult** [comment]
@apotonick 

Any ETA on the release of the delete, add, replace, etc for collections? 
(And a nice sample :-) )
Bought your book (nice!), but I'm still stuck while working on a complex(er) form.

**Comment by apotonick** [comment]
Yeah @the-ult, collections with additional semantics will go into the next chapter. I'm working on collection semantics in Representable/Reform right now, and will start writing the actual chapter when I finish the "Early-2015-Conference-World-Tour"! :wink:

**Comment by the-ult** [comment]
Thanks :-)

And good luck ;-)

**Comment by apotonick** [comment]
This is discussed in chapter 7: Mastering forms. :beers:
