### ISSUE TITLE
parameter handling in operation/controller when request format is :json

### ISSUE THREAD

**Issue by hellvinz** [apotonick/trailblazer#33]
Hi,
I have trouble getting the rational behind https://github.com/apotonick/trailblazer/blob/595229e99a8d75daabd04eb94b99a8e8a13f3767/lib/trailblazer/operation/controller.rb##L64-L71

if rails is receiving this request:
```
PUT /projects/2 HTTP/1.1
Host: localhost:3000
Connection: keep-alive
Content-Length: 32
accept: application/json
Origin: http://localhost:3000
x-csrf-token: token
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36
content-type: application/json
DNT: 1
Referer: http://localhost:3000/projects/2/edit
Accept-Encoding: gzip, deflate, sdch
Accept-Language: fr-FR,fr;q=0.8,en-US;q=0.6,en;q=0.4

{"project":{"timeline":[64,63]}}
```
(note that the body is valid json)

for a standard CRUD operation of a Project concept

Rails automatically Json.decode the body (see: https://github.com/rails/rails/blob/1d85c707b633b6ed1623290fa9aff5d7fd74d05e/actionpack/lib/action_dispatch/middleware/params_parser.rb#L44), which results in the params hash containing the expected ```"project"=>{"timeline"=>[64, 63]}``` tuple.

But at the end of the unless block in operation/controller.rb, params variable will contain ```"project"=>"{\"project\":{\"timeline\":[64,63]}}"``` which I think does not make sense.

So I guess I must be missing the point, can you please enlight me?

**Comment by apotonick** [comment]
Yepp, for JSON documents you need a separate operation that won't pass in params but `request.body` into the operation.

This will be covered in a future chapter of the Trailblazer book. Sorry for making you wait but I'm currently touring and don't have much time for writing.

What exactly are you trying with your operation? Reuse it for JSON?

**Comment by hellvinz** [comment]
Yes I have a build block to handle JSON and not JSON requests. But I think I can find a workaround

In facts I encountered two other problems:
- I have a process_params! (in the controller calling the operation) that add the current_user.id in the project params, and this additional param is lost with the unless block (I didn't want to pass the user.id in the json)
- in another part of the code, I have used paperdragon and http://www.dropzonejs.com/ and because request.format is json (because dropzone is expecting json), the params becomes something like:
{ the_operation_name => the_multipart_body } that can't be handled

**Comment by apotonick** [comment]
@hellvinz That's an interesting case. I really don't like the `if` block for JSON, that was more of an experiment, so happy to change that.

We should have a test for that dropzone problem...

**Comment by apotonick** [comment]
This is fixed now: https://github.com/apotonick/trailblazer#different-request-formats

Basically, you don't need to do anything, as you want the default Rails behaviour with the pre-parsed hash. :grin:

**Comment by hellvinz** [comment]
:+1:
