### ISSUE TITLE
Still get NoMethodError: undefined method `model' for #<Catalog:0x007fe0421ae328>

### ISSUE THREAD

**Issue by HuckyDucky** [apotonick/trailblazer#43]
Hi, very excited about Trailblazer and am going through the book. Trying to convert my simplest MVC representation in Rails 4.2 over to a *concept*.  It's called *Catalog*, and it has a *name* and a *description*:
```
class Catalog <  ActiveRecord::Base
  class Create < Trailblazer::Operation
    def process(params)
      Catalog.create(params[:catalog])
    end
  end
end
```

I'm following along directly in the book in the chapter *Operations and Forms*. One thing I was confused on right off the bat is, why are we subclassing *ActiveRecord::Base* in the *crud.rb*. Isn't simply having:

```class Catalog```

sufficient for namespacing purposes? Anyway, I also have the *crud_test.rb*:

require 'test_helper'
```
class CatalogCrudTest < MiniTest::Spec
  describe "Create" do
    it "persists valid" do
      catalog = Catalog::Create[catalog: { name: "My Name", description: "My Description" }].model
      puts catalog.class.name
      puts catalog.public_methods.sort.join("\n")
      catalog.persisted?.must_equal true
      catalog.name.must_equal "My Name"
      catalog.description.must_equal "My Description"
    end
  end
end
```

I'm getting the error from my subject line. I have reviewed the *README* and have this in my *config/application.rb* file at the bottom:

```\###################
### My Settings ###
###################
# So the Trailblazer CRUD tests will run:
require "trailblazer/rails/railtie"
# Since Trailblazer's Form::ActiveRecord module is not loaded properly in Rails 4 (don't know why):
require 'reform/rails'
```
This is in Rails 4.2.1. Please help! I really want to get this going, I'm excited about decoupling the components of this brand new project. I refuse to let this turn into spaghetti!

**Comment by fernandes** [comment]
try this:

```ruby
class Catalog <  ActiveRecord::Base
  class Create < Trailblazer::Operation
    include CRUD
    def process(params)
      Catalog.create(params[:catalog])
    end
  end
end
```

**Comment by HuckyDucky** [comment]
Thanks sir. when I do that, I get this:
```
RuntimeError: [Trailblazer] You didn't call Operation::model.
```

Oddly enough, when I removed the *.model* message (and the *CRUD* inclusion), the test worked. But it seems like an accident.

I have actually never before seen this style of statement with the square brackets:

```
Catalog::Create[catalog: { name: "My Name", description: "My Description" }].model
```
but it seems to return the resulting *catalog* AR object as its results though.

**Comment by fernandes** [comment]
ohhhh I thought you knew about the model, when using CRUD, trailblazer does __not__ try to guess the model related to, so you need to specify, in your case:

```ruby
class Catalog <  ActiveRecord::Base
  class Create < Trailblazer::Operation
    include CRUD
    model Catalog # specify here the AR model
    def process(params)
      Catalog.create(params[:catalog])
    end
  end
end
```

**Comment by HuckyDucky** [comment]
OK, awesome, that explains it. But it looks like I'm still supposed to leave off the *.model* message that is specified in the book right? Because it's already returning that correctly:
```
catalog = Catalog::Create[catalog: { name: "My Name", description: "My Description" }]
```
returns the model just fine. Only:

```catalog = Catalog::Create[catalog: { name: "My Name", description: "My Description" }].model```

gives the error.

That makes me think that controller code:

```
    run Catalog::Create do |op|
      return redirect_to op.model
    end
    render action: :new
```

would be better written as:

```
    run Catalog::Create do |op_model|
      return redirect_to op_model
    end
    render action: :new
```

**Comment by HuckyDucky** [comment]
Also, I see why we're subclassing *ActiveRecord::Base* now. We're calling the *new* method later in the chapter.

**Comment by fernandes** [comment]
so everything is ok? right?

**Comment by HuckyDucky** [comment]
Yeah, I guess there have just been some things that haven't caught up with the book yet. Works out well as I have to figure some things out. Thanks for your help!

**Comment by fernandes** [comment]
no problem... thank you :)
