### ISSUE TITLE
undefined method 'form'

### ISSUE THREAD

**Issue by HuckyDucky** [apotonick/trailblazer#44]
My controller doesn't know about a helper method called "form". Code is:

```
class CatalogsController < ApplicationController

  def new
    form Catalog::Create
  end
end
```

from page 51 of the *Trailblazer* book. Must be some kind of helper I can include.

*Operation* code is:

```
class Catalog < ActiveRecord::Base
  class Create < Trailblazer::Operation
    include CRUD
    model Catalog
    
    contract do
      property :name
      property :description
      
      validates :name, presence: true
      validates :description, length: {in: 1..255}, allow_blank: false
    end
    
    def process(params)
      catalog = Catalog.new
      
      validate(params[:catalog], catalog) do |f|
        f.save
      end
    end
  end
end
```

 I'm looking...

**Comment by fernandes** [comment]
check this

https://github.com/apotonick/gemgem-trbrb/blob/master/app/controllers/application_controller.rb

**Comment by HuckyDucky** [comment]
That's the stuff. I need to follow along over there before I post any more here. Thanks once again @fernandes.

**Comment by fernandes** [comment]
hahahha ok

gemgem trb is a complete example, you can check over there :wink:
