### ISSUE TITLE
Edge case when AR table_name is overridden

### ISSUE THREAD

**Issue by HuckyDucky** [apotonick/trailblazer#45]
I'm using the *Apartment* multi-tenancy gem to silo users into separate Postgres schemas. I ran into this during testing tonight:

    NameError:         NameError: `@public.catalog' is not allowed as an instance variable name

Which comes from *Trailblazer::Operation::Controller::ActiveRecord*:

```
# Assigns an additional instance variable for +@model+ named after the model's table name (e.g. @comment).
module Trailblazer::Operation::Controller::ActiveRecord
private
  def setup_operation_instance_variables!
    super
    instance_variable_set(:"@#{operation_model_name}", @model)
  end

  def operation_model_name
    @model.class.table_name.singularize
  end
end
```

But I imagine this would cause a problem with anyone overriding the *table_name* of a particular AR model with a schema prefix, so it will probably pop up. I've changed *operation_model_name* to:

```
  def operation_model_name
    @model.class.table_name.split(".").last.singularize
  end
```
as a hack.

Is that good enough? Should I generate a PR? I would love to contribute any way I can. I have never created a pull request.

**Comment by fernandes** [comment]
hummm thats no good :crying_cat_face: 

`1`. trailblazer avoid guessing stuff (@apotonick can point right direction here), you can do something like this under your controller

```ruby
run Catalog::Create[params] do |op|
  @catalog = op.model
end
```

`2`. you can set you table_name under AR model like this

```ruby
class Catalog < ActiveRecord::Base
  self.table_name = "catalog"
end
```

this way you're gonna get the right variable set upped to your case

if you need this as a hack, you can monkeypatch under your `lib/` folder...

btw, have you set the `model Catalog` under operation?

**Comment by HuckyDucky** [comment]
Yeah, I did set ```model Catalog``` so that is working fine. Overriding the ```table_name``` doesn't help me, because since I'm doing multitenancy, I *need* that table_name to be ```public.catalogs```.

But I don't think ```@model.class.table_name.split(".").last.singularize``` is guessing at anything, since:

```
"catalogs".split(".").last == "catalog"
```
and
```
"public.catalogs".split(".").last == "catalog"

The Ruby implementation of ```String#split``` would have to change for that line to be a problem, wouldn't it?

**Comment by apotonick** [comment]
I like what @HuckyDucky suggests. When writing the `Operation::ActiveRecord` module, I didn't know about table names containing dots.

@HuckyDucky can you add a test for this, too, in your PR? It will go here: https://github.com/apotonick/trailblazer/blob/master/test/rails/controller_test.rb#L197 - anyway, I can help you with that and add the test. They're a bit too "implicit" at the moment, meaning that one test case tests a lot of things in a not-so-obvious way. Go, fork and become famous with your commit! :wink: 

@fernandes Thanks for rejecting this, now it looks as if I'm a really nice guy! :laughing:

**Comment by fernandes** [comment]
hahahahahaha thats my job, make you awesomer than you are hahahah

at least now I know I can make guesses on trailblazer (and use respond_to?) hahahah

:stuck_out_tongue_winking_eye:

**Comment by HuckyDucky** [comment]
I'm excited!

**Comment by fernandes** [comment]
kkkkkkkkkkkkkkkkkkkkkkkkkkkk amazing! :D

**Comment by HuckyDucky** [comment]
OK I'm deflated. I don't know how to write that test.

**Comment by fernandes** [comment]
I won't help you!! (then @apotonick goes helps, and saves the day! hahahaha)

just kidding... If I get some time this afternoon I write the test so you can learn how to
