### ISSUE TITLE
Can't get Capybara matchers to work with cell test

### ISSUE THREAD

**Issue by HuckyDucky** [apotonick/trailblazer#47]
Using the book as a guide, I've written the following cell test:

    require 'test_helper'

    class CatalogCellTest < Cell::TestCase

      let(:blues) { Catalog::Create[catalog: { name: "Blues" }] }
      let(:canes) { Catalog::Create[catalog: { name: "Hurricanes" }] }

      subject { concept("catalog/cell", collection: [blues, hurricanes]) }

      it do
        subject.must_have_selector ".col-lg-3 .header a", text: "Blues"
        subject.must_have_selector ".col-lg-3 .header a", text: "Hurricanes"
      end

    end

Simple enough, but the *Capybara* matchers aren't found:

    CatalogCellTest#test_0001_anonymous:
    NoMethodError: undefined method `must_have_selector' for #<Catalog::Cell:0x007fc454374680>

I looked at the *gemgem_trb* test helper, but didn't see anything specific to Capybara in there. I actually do *require* it in my *test_helper.rb* file:

    require "minitest/rails/capybara"

Oh yeah, I'm working with *Minitest*. Any help is appreciated.

**Comment by apotonick** [comment]
I had similar problems and got it working with a hack: https://github.com/apotonick/gemgem-trbrb/blob/master/test/concepts/comment/cell_test.rb#L22

Note that this will all be running nicely in Cells 4 and rspec-cells.
