### ISSUE TITLE
toplevel constant Cell referenced by Thing::Cell

### ISSUE THREAD

**Issue by jasonelston** [apotonick/trailblazer#49]
Hi,

I'm enjoying learning Trailblazer. I really like the concepts (no pun intended!) that it's trying to apply. I am, however, a little green when it comes to finding may way around Rails and I'm running into a couple of issues. I'll post about the other one in another issue if I can't resolve it (to do with the concept method working in Rspec).

I'm following through the book and I've added the items from https://github.com/apotonick/gemgem-trbrb/wiki/Things-You-Should-Know but I'm getting `warning: toplevel constant Cell referenced by Thing::Cell` errors when trying to access `Thing::Cell` from the Rails console.

I thought it might be something to do with the Rails autoload feature and the [Trailablazer Railtie](https://github.com/apotonick/trailblazer/blob/master/lib/trailblazer/rails/railtie.rb), which references `crud.rb` files but not `cell.rb` files. There's no reference to cell files in [autoloading](https://github.com/apotonick/trailblazer/blob/master/lib/trailblazer/autoloading.rb) either. My tinkering with those has been unsuccessful though. I'm wondering if I'm missing something or doing something wrong.

Any assistance would be greatly appreciated and keep up the great work.

Jason

**Comment by francois** [comment]
Jason, it means somewhere in your code you are using Thing::Cell, and Ruby is warning you that Thing::Cell does not exist but ::Cell does (a toplevel constant). Fix your reference and you'll be allright.

**Comment by jasonelston** [comment]
Thanks @francois. Yes, that's the conclusion that I came to, however I've got a `Cell` class namespaced under thing in `app/concepts/thing/cell.rb` as per the example [gemgem app](https://github.com/apotonick/gemgem-trbrb/blob/master/app/concepts/thing/cell.rb#L1):

``` ruby
class Thing::Cell < Cell::Concept
  property :name
  property :created_at

  include Cell::GridCell
  self.classes = ["box", "large-3", "columns"]

  include Cell::CreatedAt

  def show
    render
  end

private
  def name_link
    link_to name, thing_path(model)
  end

  # The public helper that collects latest things and renders the grid.
  class Grid < Cell::Concept
    def show
      things = Thing.latest
      concept("thing/cell", collection: things, last: things.last)
    end
  end
end
```

Wont `::Cell` reference the root cell/class module from the Cell gem? It seems to be as checking the class of the `::Cell` returns `module`.

``` ruby
irb(main):002:0> ::Cell
=> Cell
irb(main):003:0> ::Cell.class
=> Module
irb(main):004:0> Thing::Cell
(irb):4: warning: toplevel constant Cell referenced by Thing::Cell
=> Cell
irb(main):005:0> Thing::Cell.class
(irb):5: warning: toplevel constant Cell referenced by Thing::Cell
=> Module
irb(main):006:0> 
```

**Comment by apotonick** [comment]
I dislike the autoloader and in future versions of Trailblazer things will be required explicitly.

The Rails autoloader works fine if you have 5 classes in 5 files with 5000 lines of code each. The whole concept (no pun intended hahaha) breaks down as soon as you introduce more classes - where you don't want each class in a separate file.

An easy fix would be to load `cell.rb` here: https://github.com/apotonick/trailblazer/blob/master/lib/trailblazer/rails/railtie.rb#L9

I like this, and it will fix another issue. As soon as Trb's got a default file structure (e.g. `crud.rb`, `cell.rb`, etc.) we can require them all in the railtie.

**Comment by jasonelston** [comment]
Thanks @apotonick. I've updated the `Railtie` as per the following. Seems to be work.

https://github.com/jasonelston/trailblazer/blob/cell-autoload/lib/trailblazer/rails/railtie.rb

I haven't done any pull requests but happy to submit if it's worthy.

**Comment by apotonick** [comment]
I think we're happy to merge this. The railtie is still a WIP of finding best practices and your fix looks very mucho OK to me.

**Comment by apotonick** [comment]
I merged it already. Thanks! :heart:

**Comment by jasonelston** [comment]
Great! Thanks for the help.

**Comment by ikelvinlemus** [comment]
i had the same problem in the version 1.0.4 of trailblazer.
i created an initializer: 
Dir.glob("#{MyEngine::Engine.root}/app/concepts/**/**/cell.rb").each do |f|
  require_dependency f
end
