### ISSUE TITLE
Operation.run return different types

### ISSUE THREAD

**Issue by bolshakov** [apotonick/trailblazer#50]
When you call operation this way it return a tuple of result and operation:

```ruby
MyOperation.run(params) #=> [true, Operation]
```

But if you pass a block it return operation.

```ruby
MyOperation.run(params) #=> Operation
```

Is it expected behavior? It looks confusing fot me

**Comment by apotonick** [comment]
This is per design.

When you call with the block, the block is only run when valid. This implies that you know the result, hence you only get the operation.

**Comment by bolshakov** [comment]
But you may be wrong iт your assumption, so it returns operation [even if Operation is invalid](https://github.com/apotonick/trailblazer/blob/master/lib/trailblazer/operation.rb#L26-L27). 

So should doable check validness of operation in the passed block. May be it's better to rewrite this part a bit:

```ruby
if block_given?
  if res
    yield op
    return op
  end
end
```

or even the whole method to always return the same type:

```ruby
def run(*params, &block) # Endpoint behaviour
  build_operation_class(*params).new.run(*params).tap do |res, op|
    yield op if res && block_given?
  end
end
```

**Comment by apotonick** [comment]
No, that is per design. It always returns the operation, but the _block_ is only run in valid case.

Reason is that you might need the operation for error handling later. The conceptual thought is as follows.

```ruby
op = Operation.() do |op|
  # do successful things here.
  return
end

error_handling(op.errors)
```

**Comment by bolshakov** [comment]
Got it, thanks
