### ISSUE TITLE
Operation returns the model

### ISSUE THREAD

**Issue by thotmx** [apotonick/trailblazer#54]
I'm trying to migrate a medium-size application  step by step to TrailBlazer.

I've created an operation to replace my old model, but I've the problem that the OperationName::Create returns the model itself.

I've this test:
```
params = { some paremeters}
my_model = MyModel::Create[my_model_name: params].model
expect(my_model).to be_persisted
expect(my_model.param1).to be(param1_value)
```  
The operation is this:
```
class MyModel < AnotherModel
  class Create < Trailblazer::Operation
     def process(params)
       MyModel.create(params[:my_model_name])
     end
  end  
end
```

The test fails because there is no model method. Because the returned class is a MyModel object not an Operation.

The only difference between the book's example and mine is that the models are using STI (Single Table Inheritance).

Am I missing something?

**Comment by apotonick** [comment]
Whatever you return in `#process` will be returned from the operation call. Usually, `#validate` is run and returns `self`.

This will fix it.

```ruby
def process(params)
  MyModel.create(params[:my_model_name])
  self
end
```

**Comment by thotmx** [comment]
The previous code itself doesn't fix the problem: 

To fix completely the problem, I needed to add this code:

```
class MyModel < AnotherModel
  class Create < Trailblazer::Operation
     attr_reader :model
     def process(params)
       @model = MyModel.create(params[:my_model_name])
       self
     end
  end  
end
```

Thanks a lot @apotonick for your guidance to solve the problem.
