### ISSUE TITLE
CRUD - scoping to current_user?

### ISSUE THREAD

**Issue by kevinansfield** [apotonick/trailblazer#55]
Forgive me if this is a naive question, but how would I make an `::Update ` call from a controller such that it scopes the `find` to the `current_user`?

eg, consider the following:

```ruby
class HorsesController < ApplicationController

  before_filter :authenticate_competitor!

  def edit
    form Horse::Update
  end

  def update
    run Horse::Update do |op|
      flash[:success] = 'Horse saved'
      return redirect_to settings_profile_path
    end

    render action: :edit
  end
  
end
```

Both the `edit` and `update` methods will currently allow any competitor to edit any other competitor's horse. How can I scope it so it uses `current_competitor.horses.find` instead?

Thanks in advance!

**Comment by kevinansfield** [comment]
I've simulated my original controller behaviour by using `process_params!` and explicitly checking that the two competitors match. It feels a bit ugly but it does mean that I can use `Horse::Update` without necessarily passing in `params[:competitor_id]` in the console or admin area.

Is this a reasonable avenue to pursue or is there a more idiomatic way to scope the find?

```ruby
class HorsesController < ApplicationController

  ...

  private

  def process_params!(params)
    params.merge!(competitor_id: current_competitor.id)
  end
  
end
```

```ruby
class Horse < ActiveRecord::Base
  class Create < Trailblazer::Operation
    include CRUD
    model Horse, :create

    ...

    private

    def setup_model!(params)
      model.competitor = Competitor.find(params[:competitor_id])
    end
  end

  class Update < Create
    action :update

    contract do
      property :competitor, writeable: false
    end

    private

    def setup_model!(params)
      if params[:competitor_id]
        competitor = Competitor.find(params[:competitor_id])
        raise ActiveRecord::RecordNotFound if model.competitor != competitor
      end
    end
  end
end
```

**Comment by apotonick** [comment]
What you do right now seems OK. However, authentication will be handled in policies in Operations and tackle just that plus fine grained access control for contracts, callbacks, etc. Patience, patience, my friend!
