### ISSUE TITLE
Operations not autoloading after modification when using spring

### ISSUE THREAD

**Issue by townhouse** [apotonick/trailblazer#56]
Posted this in #29 (Doesn't play nice with Spring in test environment?) which is closed but opening a new issue here. Sorry for duplication...

I'm still running into this issue whilst using spring with Rails 4.2.1 and trailblazer/master. Only spring stop/start loads operations after they are modified and lets me run tests.

Edit: Forgot to mention that I have followed the steps on https://github.com/apotonick/gemgem-trbrb/wiki/Things-You-Should-Know

**Comment by apotonick** [comment]
@pixeltrix Do you know how the autoloading in combination with Spring changes? :question: 

@townhouse Have you tried without Spring? Does it work OK for you? Can you setup a minimal test app so I can check it out? Thanks!

**Comment by townhouse** [comment]
Hi @apotonick!

l've tried without Spring and it works as expected. I'll setup a minimal test app for you when I get a spare few minutes later. Thanks!

**Comment by townhouse** [comment]
Hi @apotonick,

Minimal test app here: https://github.com/townhouse/trailblazer_spring_test_app

Steps to reproduce:

Run tests using spring.
Modify app/concepts/thing/crud.rb
Re-run tests with spring.
NameError: uninitialized constant Thing::Create

Following the steps without using spring works fine.

thanks!

**Comment by townhouse** [comment]
Hey @apotonick, got this working!

In master, you've reintroduced the if/else clause that checks config.cache_classes (which @pixeltrix said was unnecessary as to_prepare will only get called once in production). I can get my tests working after modifying operations by replacing the clause with just:

    ActionDispatch::Reloader.to_prepare do
      Trailblazer::Railtie.autoload_operations(app)
      Trailblazer::Railtie.autoload_cells(app)
    end

I've got no idea what I'm doing so I hope I haven't broken anything lol

Trailblazer (and the book) rocks by the way :)

**Comment by apotonick** [comment]
Thanks!!!! :heart: 

I had this setup once but something broke. Let me test.

**Comment by apotonick** [comment]
I am using the new setup now with the simplified autoloading and it works. Great, thanks for figuring that out @pixeltrix and @townhouse !!! :beers:
