### ISSUE TITLE
Operation doesn't work when request format is not html

### ISSUE THREAD

**Issue by freemanoid** [apotonick/trailblazer#58]
Here is my simple structure:
```ruby
class Thing < ActiveRecord::Base
  class Create < Trailblazer::Operation
    def process(params)
      @model = Thing.new
      validate(params[:thing], @model) do |f|
        f.save
      end
    end
  end
end

class ThingsController < ApplicationController
  include Trailblazer::Operation::Controller

  def create
    run Thing::Create
  end
end
```

When I make post request with **json** format I get an error:
```
curl -X POST -H "Content-Type: application/json" -d '{"key": "foo", "value": "bar"}' localhost:3000/things.json
```
Error:
```
NoMethodError: undefined method `keys' for "{\"key\": \"foo\", \"value\": \"bar\"}":String
from /Users/freeman/.rvm/gems/ruby-2.2.2/gems/representable-2.1.8/lib/representable/hash/allow_symbols.rb:21:in `stringify_keys'
/Users/freeman/.rvm/gems/ruby-2.2.2/gems/representable-2.1.8/lib/representable/hash/allow_symbols.rb:10:in `update_properties_from'
/Users/freeman/.rvm/gems/ruby-2.2.2/gems/representable-2.1.8/lib/representable/hash.rb:31:in `from_hash'
/Users/freeman/.rvm/gems/ruby-2.2.2/gems/reform-1.2.6/lib/reform/form/validate.rb:94:in `deserialize!'
/Users/freeman/.rvm/gems/ruby-2.2.2/gems/reform-1.2.6/lib/reform/form/validate.rb:86:in `update!'
/Users/freeman/.rvm/gems/ruby-2.2.2/gems/reform-1.2.6/lib/reform/form/active_model.rb:29:in `update!'
/Users/freeman/.rvm/gems/ruby-2.2.2/gems/reform-1.2.6/lib/reform/form/validate.rb:75:in `validate'
/Users/freeman/.rvm/gems/ruby-2.2.2/gems/reform-1.2.6/lib/reform/form/multi_parameter_attributes.rb:49:in `validate'
/Users/freeman/.rvm/gems/ruby-2.2.2/bundler/gems/trailblazer-af16f0136fa9/lib/trailblazer/operation.rb:109:in `validate'
/Users/freeman/sources/trailblazer_test/app/concepts/thing/crud.rb:11:in `process'
/Users/freeman/.rvm/gems/ruby-2.2.2/bundler/gems/trailblazer-af16f0136fa9/lib/trailblazer/operation.rb:67:in `run'
/Users/freeman/.rvm/gems/ruby-2.2.2/bundler/gems/trailblazer-af16f0136fa9/lib/trailblazer/operation.rb:23:in `run'
/Users/freeman/.rvm/gems/ruby-2.2.2/bundler/gems/trailblazer-af16f0136fa9/lib/trailblazer/operation/controller.rb:42:in `block in run'
/Users/freeman/.rvm/gems/ruby-2.2.2/bundler/gems/trailblazer-af16f0136fa9/lib/trailblazer/operation/controller.rb:74:in `operation!'
/Users/freeman/.rvm/gems/ruby-2.2.2/bundler/gems/trailblazer-af16f0136fa9/lib/trailblazer/operation/controller.rb:42:in `run'
```

This seems to happen because it converts request body to string but tries to read it as a hash:
https://github.com/apotonick/trailblazer/blob/master/lib/trailblazer/operation/controller.rb#L68-L70

Is it a correct default behaviour? Do I need to add a deserializer somewhere(I guess this is what `representable` was made for)?

**Comment by apotonick** [comment]
There's still a really early piece of code in `Controller` that changes behavior when the format is _not_ HTML. While this conceptually is correct, I will have to change this.

Plan is to provide a representer to deserialize the incoming string correctly instead of letting Rails do this with its `ParamsParser` kludge. The cool thing is: the representer is inferred from your contract, you basically don't have to do anything, but you're free to add/change/remove behavior for your JSON operation.

**Comment by freemanoid** [comment]
So what I need to do to fix it now for me?

**Comment by apotonick** [comment]
1. Send me $1,000,000 (USD) and I'll fix it.
2. Hack a workaround as follows: In https://github.com/apotonick/trailblazer/blob/master/lib/trailblazer/operation/controller.rb#L70 it happens. If you comment that line, it'll work. But be warned that I will soon change this code and make it awesome, so the JSON gets deserialized using a representer.

**Comment by fernandes** [comment]
hey @freemanoid , do you know todomvc.com? They made to compare JS implementations and backend, so I did for trailblazer, and its working with json, check it out the [controller](https://github.com/fernandes/trailblazer-todomvc/blob/master/app/controllers/todos_controller.rb) and the [operation](https://github.com/fernandes/trailblazer-todomvc/blob/master/app/models/todo.rb) hope it helps you :)

ps: Now that you don't need to send $1,000,000 (USD) to @apotonick you can send me half :stuck_out_tongue_winking_eye:

**Comment by freemanoid** [comment]
Thank you guys. @fernandes I used your example and now I have this:
```ruby
class ThingsController < ApplicationController
  include Trailblazer::Operation::Controller

  respond_to :json

  def create
    respond Thing::Create do |op, format|
      format.json { render status: :created, json: op.to_json }
    end
  end
end

class Thing < ActiveRecord::Base
  class Create < Trailblazer::Operation
    include CRUD, Responder, Representer

    model Thing, :create

    contract do
      property :name

      validates :name, presence: true
    end

    def process(params)
      validate(params) do
        contract.save
      end
    end

    class JSON < self
      representer do
        property :name
      end
    end

    builds do |params|
      JSON if params[:format] == :json
    end
  end
end
```

Current issue is:
```
NoMethodError (undefined method `new' for nil:NilClass):
```
from https://github.com/apotonick/trailblazer/blob/master/lib/trailblazer/operation/responder.rb#L22
The only solution I see is to add something like
```ruby
self.class.build_representer_class if self.class.representer_class.nil?
```
to `#to_json`

What did I made wrong? Could you help me?

[1]: https://github.com/apotonick/trailblazer/blob/master/lib/trailblazer/operation/representer.rb#L14-L16

ps. please, send me the photos of your credit cards (both sides) so I can split $$$ between two of you!  :smile:

**Comment by apotonick** [comment]
Hahahahahahahahahahaha! :laughing: 

Your fix is correct. This is really early code that I need to review. Gimme a few.

**Comment by fernandes** [comment]
we accept paypal :smile: 

good point, I'm gonna update todomvc to work with latest trailblazer, good catch :wink:

**Comment by apotonick** [comment]
I am looking into that right now.

Wondering if we should enforce using a representer? Or offer to stick with the form and simply deserialize params which is already parsed by Rails?

But this might confuse people even more?

**Comment by apotonick** [comment]
AAaah, and now I also remember the problem(s) and that I still need to invest some time into that. @freemanoid Are you happy to try out some stuff?

**Comment by freemanoid** [comment]
@apotonick what do you think I'll answer if I've tried trailblazer already? :wink:

**Comment by apotonick** [comment]
Good boy, that's why I like you! :heart_eyes: 

When you define a (redundant) representer on the operation (as you do), does that throw an error?

Trailblazer will soon be able to automatically build a generic representer from the contract, but until now, can you try with the manual one?

**Comment by freemanoid** [comment]
What do you mean?
I thought I already define representer "manually":
```ruby
class JSON < self
  representer do
    property :name
  end
end

builds do |params|
  JSON if params[:format] == :json
end
```

Could you clarify your request?

**Comment by apotonick** [comment]
Can you come join us on #trailblazer on IRC (Freenode) for a minute?

**Comment by apotonick** [comment]
The solution is this.

```ruby
builds do |params|
  JSON if params[:format] == "json"
end
```
