### ISSUE TITLE
Composed Forms and Operations

### ISSUE THREAD

**Issue by townhouse** [apotonick/trailblazer#64]
Hi apotonick!

Loving Trailblazer and the book (next chapters please!!).

I'm trying to setup a composed form and would appreciate some help on what the operations etc. should look like.

I have two ActiveRecord models, Account and User. I want to create a concept called Signup (I haven't decided yet whether Signup needs to be an ActiveRecord model or a plain ruby class) which creates an account and a user at the same time from data entered into a single form. What should the Signup class look like? The operation (specifically Create)? The controller?

There are examples in the book of nested forms but an example of this type of composed form would be really useful.

thanks!!

**Comment by apotonick** [comment]
Chapter 9 introduces `SignUp` :grimacing: 

What about this?

```ruby
module Session
  class Signup < Trailblazer::Operation
    contract do
      include Reform::Form::Composition
      property :email, on: :account
    end

    def setup_model!(params)
      contract!(user: User.find(params[:user_id]), account: Account.find(params[:account])) # this will do @contract = Session::Signup.contract_class.new(user: user, account: account)
    end

    def process(params)
      validate(params) do # here, the composition contract is already created.
```

The controller will be identical to the ones we discuss in the book. The whole point is to intantiate the contract manually as it's a composition.

Once I run into that a few times, I might make it simper in an operation to have `Composition` contracts.

**Comment by townhouse** [comment]
Ah, interesting, thanks for the example.

What I'm trying to do is basically Step 3: Extract Form Object from http://blog.codeclimate.com/blog/2012/10/17/7-ways-to-decompose-fat-activerecord-models/ where the Signup class is responsible for creating the Account and User models.

How would you model this exact functionality in Trailblazer?

Looking foward to chapter 9!! :smiley:

**Comment by apotonick** [comment]
"Extracting form object" to me sounds like introducing a Reform object, and my previous example does exactly what's described in this blog post, plus giving you a container for additional logic, which is the operation! :wink:

**Comment by townhouse** [comment]
Lol touché!! :laughing: 

Based on your example and the book / source of the demo app I managed to get something working.

````ruby
module Signup
  class Create < Trailblazer::Operation

    contract do
      include Reform::Form::Composition

      property :name, on: :account
      property :full_name, on: :user
      property :email, on: :user

      model :signup, on: :account

      validates :name, :full_name, :email, presence: true
    end

    def setup_model!(params)
      contract!(user: User.new, account: Account.new)
    end

    def process(params)
      validate(params[:signup]) do |f|
        f.save
        create_membership!
      end
    end

    private
    def user
      contract.model[:user]
    end

    def account
      contract.model[:account]
    end

    def create_membership!
      account.users << user
    end

  end
end
````

In signups_controller.rb
````ruby
class SignupsController < ApplicationController
  include Trailblazer::Operation::Controller

  def new
    form Signup::Create
  end

  def create
    run Signup::Create do |op|
      return redirect_to root_url
    end

    render :new
  end
end
````

Because Signup is just a module and not an ActiveRecord model I didn't include CRUD and could only get it to work as I needed it by using `model :signup, on: :account` - is that right or is there a better way to deal with this case?

Also, I have an explicit callback `create_membership!` in the process method. Because I'm not including the CRUD module, unlike the book examples, the only way I could access the created models was via `contract.model[:account]` and `contract.model[:user]` - Is that right or is there a better / more Trailblazer-y way of doing this?

Thanks for taking the time to answer my questions :smile:

**Comment by apotonick** [comment]
That looks correct to me. As I said, we can always streamline this case.

I do not understand why you don't use a nested setup here, as you eventually add the user to the account, anyway? You could simply do

```ruby
contract do
  # ..
  property :user, populate_if_empty: User do 
    # ..
```

This will associate the user to the profile once you `save` the contract.

On the other hand, I like that we discuss how to do compositions here, so maybe I can add that to the docs.

**Comment by townhouse** [comment]
Thanks for the advice. Switched to a nested setup and it's cleaned up my code :thumbsup:

**Comment by apotonick** [comment]
Cool! Thanks for coming up with this, I should definitely talk about composition forms in operations in the docs. :beer:

**Comment by townhouse** [comment]
Thanks for coming up with Trailblazer! :smile:

**Comment by ziaulrehmandevsinc** [comment]
Great discussion here.
I am facing a similar problem, but issue is that i can't use nested form as my both models are completely different and related to some 3rd entity which is not being used in current form.

Only part i am doing something wrong is with model here, i defined a separate form with :on and everything. But i don't know how do I tell 2 models in these lines:
```
class Show < Trailblazer::Operation
    include Model
    model First
```

I tried silly things like:
```
    model [:First, :Second]
```

```
    model [First, Second]
```

But obviously they didn't work.

I was wondering if @townhouse  or you sir @apotonick  maybe guide me a bit.

**PS:** I recently started working on trailblazer, that project includes trailblazer 1 and we cannot currently migrate to v2. But i am really excited about v2 too after seeing all the goodies in v1. And i have become fan of @apotonick ! :1st_place_medal:

**Comment by apotonick** [comment]
Hey @ziaulrehmandevsinc, thanks! :boom: You can avoid the simple_form bug by telling `simple_form_for` the `:url` in the view, it will disable some of its horrible magic and won't throw this bug.

**Comment by ziaulrehmandevsinc** [comment]
Sorry to bother you, [this issue](https://github.com/trailblazer/reform/issues/41) solved my problem.
I was already using url: so. :relieved: 

Will keep annoying you by updating here for any issues/updates that come up regarding this. Just for the sake of reference for anyone else trying to do the same. :nerd_face: .

**Comment by ziaulrehmandevsinc** [comment]
Stuck on another point, sorry to ask again.
I am receiving all parameters as they should be received but somehow, reform form is initiated with old values from DB(in update case). I checked in a validation function i have wrote in reform form, self.inspect yields old values persisted in DB also does not include any virtual properties. Stuck on this for about an hour, any help will be great. Thanks.

**Comment by apotonick** [comment]
https://gitter.im/trailblazer/chat
