### ISSUE TITLE
Trailblazer::Operation::Representer is not autoloaded.

### ISSUE THREAD

**Issue by undergroundwebdesigns** [apotonick/trailblazer#65]
Looks like a line for the Representer module needs to be added to https://github.com/apotonick/trailblazer/blob/master/lib/trailblazer/autoloading.rb.

If I have some time in the next few days I'll submit a PR, but I wanted to make a note for now so it's documented. Should be an easy fix.

**Comment by apotonick** [comment]
:laughing: It probably took longer to write this issue than to fix it! :smile: Want to submit a quick PR?
