### ISSUE TITLE
overriding to_param

### ISSUE THREAD

**Issue by paulofabiano** [apotonick/trailblazer#67]
Hi, guys! Not sure if this is an issue but, here it goes.
I have an operation called Client::Create for my client model. I want to be able to find objects not by id but for uuid property. So, I overrided the to_param method on my model, like this:

def to_param
    uuid || id #need id because in admin I still use just the id.
end

when I try to access the following route, I get an error: 
 /dados-pessoais/432986e2-a2b4-44e5-a606-c2a9f8bbd654/entrega-do-cartao
Couldn't find Client with 'id'=432986e2-a2b4-44e5-a606-c2a9f8bbd654

Any thoughts about it?

Thanks,
Paulo

**Comment by apotonick** [comment]
You have to override the finder in your operation, of course. There's no way the operation can know that it now has to do `Client.find_by(uid: ...)`.

https://github.com/apotonick/trailblazer/blob/master/lib/trailblazer/operation/crud.rb#L58

You need to override `Operation#update_model`.

```ruby
class Client::Create < Trailblazer::Operation
  def update_model(params)
    Client.find_by(uid: params[:id])
  end

```

**Comment by paulofabiano** [comment]
Thanks, my friend! It's so simple that now I feel stupid hehehe.
