### ISSUE TITLE
Suggestion: #success and #failure response blocks

### ISSUE THREAD

**Issue by mrbongiolo** [apotonick/trailblazer#68]
Hi, I've been playing around with trailblazer and really liking it, tbh it's already running in production on one of my projects :D

I'm basically just using the operations concept, but still with the "default" rails file structure, since I didn't wanted to move completely into the Trailblazer structure.

I'm not sure if this was suggested before, or it might be even way too off of what you have planned, but while I was using the operations I found myself wanting something like this:

```
Api::Customer::Create do |operation|

  operation.success do |contract, model|
    render json: { customer: Api::CustomerRepresenter.new(model) }
  end

  operation.failure do |contract, model|
    render json: { errors: contract.errors.messages }, status: :unprocessable_entity
  end
end
```

**Comment by apotonick** [comment]
Why don't you simply to that?

```ruby
operation = Api::Customer::Create.run(params) do |operation|
  return render json: { customer: Api::CustomerRepresenter.new(model) }
end

render json: { errors: operation.contract.errors.messages }, status: :unprocessable_entity
```

Documented here: https://github.com/apotonick/trailblazer#run-style

While I do love DSLs for declarative means (e.g. defining contract properties) I am not a big fan of operational DSLs. We can talk about a mix of your and my code, anyway.

BTW, operations can handle representers, too (Roar representers). This will be discussed in the _HTTP APIs_ chapter of the Trailblazer book, but here are the docs: http://trailblazerb.org/gems/operation/representer.html

**Comment by mrbongiolo** [comment]
Hey Nick, thanks for your answer.

That's exactly what I'm doing right now, and it works, but I guess I can be accused of being a DSL bitch hahaha, that is why I suggested that style.

Anyway, it really depends if you and the community think that this might improve the use of the Operations or not.

I was trying to use the representer (with version 0.3.3) and it gave me some strange require and load errors, I'll check again and report an issue if needed.

**Comment by apotonick** [comment]
You probably need to include the Roar gem into your Gemfile (re. the load issue)?
