### ISSUE TITLE
Does policy actually work yet?

### ISSUE THREAD

**Issue by AndrewSwerlick** [apotonick/trailblazer#69]
I am trying to use the policy feature inside of an operation, but as far as I can tell it's not wired up yet. Is this feature still being worked on, or am I missing something?

**Comment by MatthewHeath** [comment]
It doesn't work yet. I believe Nick is still working on it.

**Comment by fernandes** [comment]
hi guys... I suggested policy on https://github.com/apotonick/trailblazer/pull/41

but many things changed, like collection, scope.. and we are still designing the policy feature, ask for notification on PR#41 that I'm gonna post a message there once its ok

thank you

**Comment by apotonick** [comment]
Policy will come soon, as I started working on chapter 10 _Authorization and Polymorphism_. A first version should be available in 2 weeks, when I returned from my conf trip. :beers:

**Comment by apotonick** [comment]
Please start testing right away: https://github.com/apotonick/trailblazer/tree/policy

**Comment by undergroundwebdesigns** [comment]
Where would you like feedback on the policy branch? Here, or in separate issues? 

I've been playing with it... so far so good, though I've noticed that doing `present Object::Update` in the controller runs (and potentially errors out on) my update policy. Makes sense, but are there plans to make that more flexible in the future? There will definitely be cases where showing an object is allowed, but updating it isn't.

**Comment by apotonick** [comment]
Interesting idea, @undergroundwebdesigns! Maybe we should have a separate "present" policy?

**Comment by fernandes** [comment]
@apotonick thats why I suggested:

```ruby
policy do
  def create?
    user.admin?
  end

  def update?
    user.admin?
  end

  def show?
    user.can_show?
  end
end
```

then in the case @undergroundwebdesigns said, we could just use:

```ruby
class Index < Trailblazer::Operation
  include Collection
  
  policy do
    # once we don't have an action defined, we define on policy
    policy_action :index
    def index?
      false
    end
  end
end
```

**Comment by apotonick** [comment]
I am still thinking about which one I like better: @fernandes's one "global" `policy` block with all contexts defined there, or my suggestion where there's one `policy` block per operation.

**Comment by undergroundwebdesigns** [comment]
Maybe just as simple as allowing a second policy action to be specified that, if given, is used for the `form`, `perform` etc type controller calls? So:
```
class Update < Trailblazer::Operation
  include Policy::Pundit

  policy ThingPolicy, :update?, :show?
end
```
(I'm coming at this from a perspective of using the Pundit integration).

The second method arg could be optional, and if it's not provided you can use the first one for everything, which keeps the current interface.

For the inline, maybe just another keyword (perform_policy?) to specify more granular policy conditions? e.g.
```
class Update < Trailblazer::Operation
  include Policy::Pundit

  policy do
    # some condition
  end

 perform_policy do
    # some other condition
  end
end
```

**Comment by fernandes** [comment]
no problem, you can do policy block `per operation`:

```ruby
class Thing < ActiveRecord::Base
  class Create < Trailblazer::Operation
    include CRUD, Policy
    action :create

    model Thing

    policy do
      def create?
        user.admin?
      end
    end

    def process(params); self end
  end

  class Update < Create
    action :update
    policy do
      def update?
        # here you can verify if params is updating so
        # you can differ show and update
        user.admin?
      end
    end
  end

  class Publish < Create
    action :update # so will check using `update?` method
  end
end
```

**Comment by apotonick** [comment]
@fernandes In your case, you have to know/think of a method name, e.g. `#create?`. This is redundant, as the operation knows it will _create_ something. On the other hand, your (or, the pundit style) is better to inherit and override. I have an idea, let me hack on it a little bit more.

So excited we finally have this concept in Trb! :fireworks: :tada:

**Comment by fernandes** [comment]
redundant? aren't you the Sir "I-don't-like-implicit-magic-happening" ? hahahah

the operation knows its creating something, but I don't like the idea of implicit ACL because its the security of the system, as safer, better

I'm waiting for your hack :stuck_out_tongue_winking_eye:

**Comment by the-ult** [comment]
It's looking promising already! :+1:

**Comment by apotonick** [comment]
This is now merged in master and fully documented. http://trailblazerb.org/gems/operation/policy.html
