### ISSUE TITLE
Ajax (remote :true) form is broken by controller "run" helper

### ISSUE THREAD

**Issue by johnlane** [apotonick/trailblazer#82]
I have been converting a form to use Ajax and have encountered a strange behaviour that I think is occurring in the `run` controller helper. Everything works fine if the form is submitted normally but if `remote: true` is used then its data in the `params` hash gets converted into a `String`. This breaks the validation processing because it doesn't expect a `String`.

This is what I get:

     NoMethodError (undefined method `has_key?' for #<String:0xc46fe04>):
     app/concepts/user/crud.rb:163:in `process'
     app/controllers/users_controller.rb:35:in `create
         
which happens because `params` gets altered on its way into the operaiton:

Before (in the controller):

    Params: ActionController::Parameters
    Form Data: ActionController::Parameters

After (in the operation#process)

    Params: ActionController::Parameters
    Form data: String
        
My controller code is like this:
```ruby
    run User::Create do |op|
      return redirect_to op.model
    end 
    respond_to do |format|
      format.js   { render js: concept('user/cell', @operation).(:show_ajax) }
      format.html { render action: :new }
    end 
```        
If I change my controller code so that it doesn't go through the `run` controller helper, the problem goes away:
```ruby
    res, @operation = User::Create.run(params)
    if res 
      return redirect_to @operation.model
    else
      respond_to do |format|
        format.js   { render js: concept('user/cell', @operation).(:show_ajax) }
        format.html { render action: :new }
      end 
    end                             
```

**Comment by apotonick** [comment]
What `Content-type` is your request and what TRB version are you on?

**Comment by johnlane** [comment]
* trailblazer (1.0.0)
* trailblazer-rails (0.1.3 c73247b)

The content type on the request is `application/x-www-form-urlencoded`. I have not altered the Rails defaults. The post data is received correctly as I can demonstrate by viewing it in the controller. However, by the time it's accessible in the operation, the form data (i.e. the contents of the `user` hash within `params`) has been encoded as a string where it wasn't like that in the controller.

In the controller,. I can do `params[:user][:title]` but once I'm in the operation, `params[:user]` is a `String`.
