### ISSUE TITLE
params are not passed in options hash within prepopulate! contract method

### ISSUE THREAD

**Issue by acaron** [apotonick/trailblazer#87]
Missing `options[:params]` key within `prepopulate!(options)` inside an operation contract (Reform).

**Comment by acaron** [comment]
I found the faulty line: `params  = options.delete(:params) || self.params` (https://github.com/apotonick/trailblazer/blob/master/lib/trailblazer/operation/controller.rb#L57) but if you do `params  = options.has_key?(:params) ? options[:params] : self.params` you can add `options[:params] = self.params` to `form` and `respond`. BUT, this method is also called right after: `process_params!(params)` which makes me think that the params can be changed if you override this `process_params!`. So the `options[:params]` doesn't fit anymore.

**Comment by audionerd** [comment]
I'm running into this issue as well. 

The [docs for Operation::Controller](http://trailblazer.to/gems/operation/controller.html) seem to indicate that [`process_params!` can be used to modify the controller's params before the operation is run](http://trailblazer.to/gems/operation/controller.html#normalizing-params), and that [the result should be available as `options[:params]` within `populate!`](http://trailblazer.to/gems/operation/controller.html#options-for-prepopulate)

For now, I'm working around the issue by overriding `operation_for!` in my controller and setting `options[:params] = params` there myself, after it's been processed, e.g.:
```ruby
def operation_for!(operation_class, options, &block)
  [...]
  process_params!(params)
  options[:params] = params
  [..]
end
```

This is mainly just to merge in `current_user` so I can use it from `populate!` method:

```ruby
def process_params!(params)
  self.params = self.params.merge(current_user: current_user)
end

**Comment by apotonick** [comment]
@audionerd I added `Controller#params!` that allows returning an arbitrary params object: http://trailblazer.to/gems/operation/controller.html#normalizing-params

@acaron The params key now gets properly passed through to `prepopulate!`.
