### ISSUE TITLE
Best place to implement to_model / from_model conversions

### ISSUE THREAD

**Issue by konung** [apotonick/trailblazer#88]
Hi.

Really love the concept of trailblazer. @apotonick  - Nick thanks of pointing me here by way of reform from roar! 

This is a conceptual question about Trailblazer
Just got the book and something that I've seen on a number of projects came to my mind. 

I deal with some legacy apps and tables ( old PHP scripts, with crappy non-normalized tables runing MyISAMI MySQL 5.0). Those apps are still live and pull data from even older dbase (dbf) applications

So in order to pull data  back and forth between legacy parts and new parts I have  some models like this

````ruby
class OldPart < ActiveRecord....

  def to_product
    p = Product.new
    p.name = self.old_style_name.gsub(some clean up magic)
    ......
  end
end
````

Old tables are horrible - I have some tables with 130 fields, that I split into 10 models / tables in the new setup, doing some heavy cleanup and validation on the way

Based on what I'm reading in docs model is not the place for it.

What would you suggest?

**Comment by konung** [comment]
Ok Nevermind - I asked this as I was reading page 44 of the book, on page 45 it literally has an answer: 

No one requires you to formulate
your complete high-level API right now! You’re gonna be surprised how thinking about building
applications shifts from “Where do I add this in which model?” to writing a new operation whenever
you expose a new function to the public.

**Comment by apotonick** [comment]
And, this kind of code can also go into twins: decorator objects that allow to compose domain objects from different sources (probably leveraging ROM at some point). :stuck_out_tongue_winking_eye: Not sure how much I will go into detail with that in the book, but there will be docs. One. final. day.
