### ISSUE TITLE
Trailblazer doesn't find models in app/models/SUBFOLDER

### ISSUE THREAD

**Issue by konung** [apotonick/trailblazer#89]
Hi

Trying out Trailblazer on an fairly big app - with over 150 models that are orgnized in subfolders by "concept" inside models folder - some of them are STI tables and some are are jsut related

like so

app
-- models
---- rates
------ rate.rb
------ customer_discount_rate.rb
------ customer_pricing_rate.rb 
---- legacy_tables
------ legacy_part.rb
------ legacy_order.rb

etc.

Trailblazer loads models that are inside models folder, but not in the subfolders

So this code fails

```` ruby
# app/concepts/rate/crud.rb
 class Rate < ActiveRecord::Base
  class Create < Trailblazer::Operation
    def process(params)
      @model = Rate.create(params[:rate])
    end
  end
end
````
````ruby
No such file to load -- /RAILS_ROOT/app/models/rate (LoadError)
 # replaced app path to RAILS_ROOT for security
````

If I move rate.rb to models/ directly - it works. But if I move all of my model layer into models/ it's going to be a mess. :-( What am I missing? ANy ideas?

**Comment by apotonick** [comment]
You are not following Rails autoloading naming scheme. I wonder how that worked before?

You can load the model manually using `require_dependency` in your operation files instead of moving files. Don't move files, your file structure seems fine to me.

The loading of models is very tricky because Rails completely brainwashed our understanding of dependencies. We will keep working on a nice solution here (probably a list you have to configure manually, explicit over implicit), until that is ready to go, please do the manual requirements! :beer:

**Comment by konung** [comment]
Found the culprit
https://github.com/trailblazer/trailblazer-rails/blob/master/lib/trailblazer/rails/railtie.rb#L10

This should be  as more generic version
````ruby
Dir[Rails.root.join('app', 'models', '{**/**}')].find{|p| p.include?(model + '.rb')}
````
or since we are in Rails and all the models should already be in the autoload_paths and we can just search there  by selecting paths with 'models/' and than matchi model/ file name

````ruby
 Rails.configuration.autoload_paths.select{|fp| fp.include?('/models/')}.find{|p| p.include?(model + '.rb')}}
````

**Comment by konung** [comment]
I actually sort of used a homegrown simplified version of Trailbalzer  here are  a couple of lines from my config/application.rb

````ruby
   config.autoload_paths += %W(#{config.root}/lib) # loads extra bits of useful code like my implemention of false.to_human and barcoding lib:-)
    config.autoload_paths += Dir[Rails.root.join('app', 'navigation_renderers', '{**/**}')] # simple_navigation
    config.autoload_paths += Dir[Rails.root.join('app', 'models', '{**/**}')] # my deeply nested models
    config.autoload_paths += Dir[Rails.root.join('app', 'outlines', '{**/**}')] # similar to what representer / roar do - to / from various formats like CSV, XLS, JSON, TXT in PORO files
    config.autoload_paths += Dir[Rails.root.join('app', 'services', '{**/**}')] # basicly what Trailblazer Operations are 
````


Trailblazer just takes what I was doing manually on a whole another level, and makes it consistent - my implementations are less so.

**Comment by apotonick** [comment]
Haha, cool.

I will introduce an explicit configuration list of how models get loaded. Too many people use too many different styles, and even though Trailblazer introduces a more intuitive file structure I don't want to make developers having to rearrange their model directories, etc. I think a clever configuration will save us a lot of trouble and need to explain.

Thanks, this is a cool different use case which will help designing that file. You have to help me on this, though. Come join the Gitter channel! :heart:

**Comment by konung** [comment]
Ok here is my autoload hack

overwriting  config/initializers/trailblazer.install.rb

````ruby
module Trailblazer
  class Railtie < ::Rails::Railtie
    def self.autoload_operations(app)
      Dir.glob("app/concepts/**/crud.rb") do |f|
        path  = f.sub("app/concepts/", "")
        model = path.sub("/crud.rb", "")

        #require_dependency "#{app.root}/app/models/#{model}" # load the model file, first (thing.rb).
        require_dependency Dir.glob("app/models/**/**").find{|p| p.include?(model + '.rb')} # load the model file, first (thing.rb).

        require_dependency "#{app.root}/#{f}" # load app/concepts/{concept}/crud.rb (Thing::Create, Thing::Update, and so on).
      end
    end
  end
end

````

Works!
