### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by ZimbiX** [apotonick/trailblazer#90]
- http://www.trailblazerb.org/ shows a GitHub 404: "There isn't a GitHub Pages site here."
- http://trailblazerb.org/ shows a DNS error in Chrome: "ERR_NAME_NOT_RESOLVED"

**Comment by apotonick** [comment]
The new official domain is http://trailblazer.to - sorry, I'm still fixing the redirects.

**Comment by timoschilling** [comment]
can be closed
