### ISSUE TITLE
Default implementation of Operation#process

### ISSUE THREAD

**Issue by monkbroc** [apotonick/trailblazer#95]
`Operation#run` sends itself the `process` message, but doesn't define a default implementation.

There are default empty implementations for `model!`, `setup_params!`, etc. Why not have a default implementation of `process`?

**Comment by apotonick** [comment]
True. I once left it out because I thought it's easier to understand for newcomers.

**Comment by monkbroc** [comment]
Since it's a tiny change do you want to do it yourself if you think it's a good change? I don't want to waste your time with a PR for such a tiny thing.

**Comment by apotonick** [comment]
You mean, just an empty method?

**Comment by timoschilling** [comment]
@monkbroc can you show a use case for a Op with a empty `process` method?

**Comment by monkbroc** [comment]
I'd like to be able to extend my operations with other modules similar to `Policy` and `Model` and be good a collaborator by calling `super` on the extended methods.

```ruby
module Trailblazer
  class Operation
    module ValidateAndSave
      def self.included(includer)
        includer.extend DSL
      end

      module DSL
        def self.extended(extender)
          extender.inheritable_attr :params_key
        end

        def validate_and_save(key)
          self.params_key = key
        end
      end

      private

      module Process
        def process(params)
          # Be a good extension and call super
          # BUT raises NoMethodError super: no superclass method `process'
          super
          validate(params[self.class.params_key], &:save) if self.class.params_key
        end
      end
      include Process
    end
  end
end

# Update an existing task
require "trailblazer/operation/validate_and_save"
module Tasks
  class Update < Trailblazer::Operation
    include Model
    include Policy
    include ValidateAndSave
    model Task
    action :find
    policy TaskPolicy, :update?
    contract Contract
    validate_and_save :task
  end
end

```

**Comment by monkbroc** [comment]
I'll close this for now.
