### ISSUE TITLE
process_params! only works with destructive params changes incompatible with lotus controllers

### ISSUE THREAD

**Issue by davidpelaez** [apotonick/trailblazer#98]
Hi.

I'm using Trailblazer with Lotus. In lotus params are not regular hashes but special objects so it's necessary to call `to_h` on them either before calling an operation or inside the operation before passing them to `validate`.

Because of Trailblazer's controllers helpers current usage of `process_params!` in https://github.com/apotonick/trailblazer/blob/master/lib/trailblazer/operation/controller.rb#L53 I must modify the params inside the operation and cannot do it inside the controller. This is because lotus controllers are similar to Operations in that they don't use instances and pass the params object as arguments, not as instance variables.

Given this if I implement `process_params!(params)` and I try to modify `@params` within that method the value of `params` after the normalization method is actually the same params given to the controller `call` method, it's totally unrelated to the instance variable with the same name.

This is unnecessary and could be easily fixed by adding `process_params(params)` (without the bang implying destructiveness) and passing the result as the params to the operation. 

Instead of this:
```ruby
process_params!(params)
res, op = Trailblazer::Endpoint.new(operation_class, params, request, options).(&block)
```

Something like this:
```ruby
# make process_params an identity by default
def process_params(params)
  params
end

# in operation_for!(operation_class, options, &block)
params = process_params(params)
res, op = Trailblazer::Endpoint.new(operation_class, params, request, options).(&block)

# in the controller I could do
def process_params(params)
  params.to_h
end
```
This would work with Rails controllers as well as Lotus controllers and it feels to me more in line with Trailblazers proposed usage of Ruby objects.

What do you think?

**Comment by davidpelaez** [comment]
It seems this can be handled to inside the operation as mentioned in http://trailblazer.to/gems/operation/api.html#callstack

"Override #params if you want to use a different params hash - which you simply return from this method. This allows to keep the original params immutable."

This is documented by unreleased in 1.0.4 https://github.com/apotonick/trailblazer/blob/v1.0.4/lib/trailblazer/operation.rb#L92-L95 so it currently doesn't work.

In the meantime I can implement `setup_params!(params)` to make it work.

I checked the code on master and I think it would solve my issue but it brings unwanted coupling because the operation now has to assume some interface of it's provided params. This shouldn't prove a big problem because on a has I can call `to_h` in the same way that I can on an instance of Lotus params, but it's not as clean as handling things in the controller and letting the operation always assume it's been given a hash.

**Comment by apotonick** [comment]
Hi David,

my plan was to introduce the same API in `Endpoint` with an identical call stack, so you can hook in the method that suits you best.

In future versions, this will be a functional pipeline the same way we do processing pipelines in Representable 2.4.

You're right, some code must sit in the controller (or, endpoint, or `Lotus::Action`) and hence we need a tiny bit of parameter processing there which should not be in the operation.

You owe us a blog post about Lotus + TRB, I'm super excited to see what you do (and so is @jodosha)! :beers:

**Comment by jodosha** [comment]
@apotonick :+1:

**Comment by davidpelaez** [comment]
It works as expected, thanks! :)

This is what I had before:

```ruby
module LotusParamsNormalizer
  private
  def setup_params!(params)
    @params = Hashie.symbolize_keys! params.to_h
  end
end

class BaseOperation < Trailblazer::Operation
  include LotusParamsNormalizer
  include Policy
  include Model
end
```

This is what I now have. It's on the controller so the operation is totally ignorant of this matter. It's a module that I simply include in my Lotus Controllers:

```ruby
require 'hashie'

module ControllerBase
  include ::Trailblazer::Operation::Controller
  def self.included(action)
    action.class_eval do
      expose :model, :operation
    end
  end

  private

  def params!(params)
   # I like to use Hashie to use symbols at all times
    Hashie.symbolize_keys! params.to_h
  end

end
```

I'm working on an example app to show how to use Trailblazer with Lotus. I'll let you know when it's ready because Lotus is so flexible that I have found several different approaches. I think the smartest one is related to the Endpoint approach, but I don't totally understand it so I'll just open another issue to have that conversation.
